.github/settings.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/2)
=> chore: Add github settings for CI required checks.

.github/CODEOWNERS, .github/workflows/ci.yml, Dockerfile, heroku.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/3)
=> chore: Add web dockerfile and heroku config.

.heroku/default.conf, .heroku/wasm.cpp, Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/4)
=> chore: Set the right port when launching on heroku.

.dockerignore, .heroku/Dockerfile, .heroku/default.conf, .heroku/entrypoint.sh, .heroku/keys, .heroku/websockify/go.mod, .heroku/websockify/go.sum, .heroku/websockify/websockify.go, heroku.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/9)
=> feat: Add bootstrap node behind websocket on heroku.

heroku.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/13)
=> chore: Fix heroku build for real.

lib/add_contact_page.dart, lib/contact_list_page.dart, lib/strings.dart, test/widget_test.dart
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/16)
=> feat: Add an add contact page

.github/workflows/ci.yml, android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, lib/add_contact_page.dart
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/18)
=> chore: Fix Flutter 2.10 build, target it in CI

lib/app_state.dart, lib/contact_list_page.dart, lib/profile.dart, lib/settings.dart, lib/strings.dart
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/19)
=> feat: Add state and the ability to set the nick and status message

lib/chat_page.dart, lib/contact_list_page.dart, lib/db/database.dart
Each contact now has a unique ID so we can link messages to the correct
contact.
This requires a rerun of the prepare scripts in order to generate the
new database schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/24)
=> feat: Start keeping messages in the database

.github/workflows/ci.yml
See https://codecov.io/gh/robinlinden/bTox/tree/e25e102ac83df22e9aac206604f3cf10035633cd/lib for a successful run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/27)
=> chore: Measure code coverage

.github/workflows/ci.yml, pubspec.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/28)
=> chore: Target flutter 2.10.3

.github/workflows/ci.yml, linux/flutter/generated_plugins.cmake, pubspec.lock, windows/flutter/generated_plugins.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/30)
=> chore: Target Flutter 3

.github/workflows/ci.yml, .metadata, .restyled.yaml, ios/Flutter/AppFrameworkInfo.plist, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner/Info.plist, ios/RunnerTests/RunnerTests.swift, lib/profile.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner/Base.lproj/MainMenu.xib, macos/Runner/Configs/AppInfo.xcconfig, macos/Runner/MainFlutterWindow.swift, macos/RunnerTests/RunnerTests.swift, pubspec.lock, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/34)
=> chore: Update flutter, dart, and dependencies

README.md
These are very basic instructions, but you probably shouldn't be building bTox in its current state unless you're a developer that already knows (or is willing to learn!) Flutter.
Resolves #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/btox/31)
=> docs: Update the readme with build instructions

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/40)
=> chore: Update github actions.

cspell.config.yaml, ios/Flutter/AppFrameworkInfo.plist, ios/Flutter/Debug.xcconfig, ios/Flutter/Release.xcconfig, ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner.xcworkspace/contents.xcworkspacedata, ios/Runner/AppDelegate.swift, macos/Flutter/Flutter-Debug.xcconfig, macos/Flutter/Flutter-Release.xcconfig, macos/Podfile, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner.xcworkspace/contents.xcworkspacedata, macos/Runner/AppDelegate.swift, pubspec.lock
Also updated dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/44)
=> chore: Update to latest ios/macos recommendations.

.github/workflows/ci.yml, android/app/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/46)
=> chore: Upload build artifacts on CI.

lib/add_contact_page.dart, lib/widgets/friend_request_message_field.dart, lib/widgets/tox_id_field.dart
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/47)
=> cleanup: Split out the add contact page into separate widgets.

.cirrus.yml, .github/workflows/pages.yml, .restyled.yaml, web/flutter_bootstrap.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/48)
=> chore: Add GitHub pages deploy workflow.

.github/workflows/ci.yml, .github/workflows/release.yml, netlify.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/53)
=> chore: Cancel PR builds when new commits are pushed.

lib/api/toxcore/tox.dart, lib/api/toxcore/tox_events.dart, lib/db/native.dart, lib/ffi/toxcore.dart, lib/models/crypto.dart, lib/providers/tox.dart, lib/widgets/main_menu.dart, test/mocks/fake_toxcore.dart
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/btox/60)
=> feat: Parse the tox core events and display them in the log.

.imgbotconfig
To comply with our commit/pr message policy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/bTox/73)
=> chore: Add configuration for imgbot.
